export const AUTH_ACTIONS = {
    AUTH_REQUEST: "AUTH_REQUEST",
    AUTH_INIT_COMPLETE: "AUTH_INIT_COMPLETE",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    FETCH_ME_SUCCESS: "FETCH_ME_SUCCESS",
    FETCH_ME_FAILURE: "FETCH_ME_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR",
} as const;